apiVersion: v1
kind: Service
metadata:
  name: art4-service
  labels:
    app: art4-devops-project
spec:
  selector:
    app: art4-devops-project
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
